### ISSUE TITLE
AnteUp Date not showing correctly 

### ISSUE THREAD

**Issue by Worldwide7477** [septor/dateplus#5]
On the newest AnteUp 2.xx everything works great except for the due date, please let me know how to change this i have tried using a different format such as 8-3-2016 but it does not work.
![2016-08-12_11-10-53](https://cloud.githubusercontent.com/assets/20016207/17627590/c31c5c4c-607f-11e6-985f-262c8cad968c.jpg)

**Comment by septor** [comment]
Please move this issue to the correct repo. I think there is already an issue open, so if you could just comment with your experience that would be super.

**Comment by septor** [comment]
Actually, it seems this issue was fixed. You'll have to make the modifications yourself, however, as I don't have time to package up an update right now. See [here](https://github.com/septor/anteup/commit/d1c38d148ec9f8d38d1c20495263205e1625ce21).

**Comment by Worldwide7477** [comment]
Thanks septor for the link that fixed it, working great now :)
